---
version: "3.8"
services:
  NN_mcstatus:
    image: p0t4t0sandwich/neuralnexus:mcstatus
    container_name: NN_mcstatus
    environment:
      - TZ=UTC
      - GIN_MODE=release
      - SERVER_URL=/
    ports:
      - "0.0.0.0:3001:3001"
    restart: unless-stopped
